apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  selector:
    matchLabels:
      app: productservice
  replicas: 1
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: emreoytun/productservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084  # Updated to match the application's port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: productservice-ssvc
spec:
  selector:
    app: productservice
  ports:
    - protocol: "TCP"
      port: 80             # Port exposed by the service
      targetPort: 8084     # Port on which the application is listening
  type: LoadBalancer
